print("  ___________")
print(" /           \\")
print("|  ^      ^   |")
print("|     /_\     |")
print("|   \_____/   |")
print(" \___________/")
print("Hello!")
name = input("What's your name?")
print("nice to meet you, " + name + "!")
